model:
  model_name: "CustomCNN"
  input_dim: 32
  output_dim: 11

training:
  batch_size: 64
  learning_rate: 0.001
  optimizer: "adam"
  reg: 0.00001
  epochs: 15
  weight_decay: 0.0001
  momentum: 0.9
  gamma: 0.6

loss:
  loss_type: "cross_entropy"

early_stopping:
  active: true
  patience: 5

saving:
  enabled: true
  dir: "saved_models/"
  name: "best_cnn.pt"